### ISSUE TITLE
文档中查看版本的参数是否不完整？

### ISSUE THREAD

**Issue by ShadowWaIker** [serverless-components/tencent-fullstack#4]
https://github.com/serverless-components/tencent-fullstack/blob/master/README.md#安装
这一节中的参看参数命令 `serverless –v` 在运行时会报错：
Serverless command "–version" not found. Did you mean "function"? Run "serverless help" for a list of all available commands.

测试后发现 `serverless --v` `serverless --version` `sls --v` `sls --version` 这几个命令才可以获取到版本信息，文档中的命令应该是少了一个 `-`

**Comment by June1991** [comment]
你是在什么环境下执行的这个命令？windows下吗？

**Comment by ShadowWaIker** [comment]
关掉所有shell(VS Code 中的终端、iTerm)之后，新建的终端和新打开的iTerm可以执行 serverless –v 并且获取版本号了，也许是更新后的sls没有正确加载？
但是我执行 sls --v 看到的版本信息是下文中的升级后的版本信息😂

环境是MacOS 10.15.4
shell是zsh

升级前的 Framework Core 好像是 1.67.2
升级后的版本信息是：
Framework Core: 1.68.0
Plugin: 3.6.6
SDK: 2.3.0
Components: 2.30.1
