### ISSUE TITLE
运行时报：roleBinder.bindQCSRole

### ISSUE THREAD

**Issue by idrex** [serverless-components/tencent-fullstack#5]
serverless ⚡ framework
TypeError: roleBinder.bindQCSRole is not a function

**Comment by tinafangkunding** [comment]
hi 请问是子账户吗？可以尝试主账户创建 slsqcsrole 角色之后试一下呢？参考 https://cloud.tencent.com/document/product/1154/43006

**Comment by idrex** [comment]
不是子账户

**Comment by idrex** [comment]
Framework Core: 1.68.0
Plugin: 3.6.6
SDK: 2.3.0
Components: 2.30.1

**Comment by tinafangkunding** [comment]
@anycodes 辛苦帮忙一起看下这个问题哈

**Comment by anycodes** [comment]
可能是组件版本变更导致的。
可以尝试npm update试一下

**Comment by idrex** [comment]
全局依赖更新了就没问题了
